### ISSUE TITLE
Is this plugin not hosted anymore?

### ISSUE THREAD

**Issue by pamartineza** [adavis/quality-checks#1]
Hi @adavis ,

I'm interested in using your plugin but after following installs instructions I get this error message, it seems the artifact or repo is not available.

Best regads

```
Error:Could not find any matches for gradle.plugin.info.adavis:qualityChecks:0.1.+ as no versions of gradle.plugin.info.adavis:qualityChecks are available.
Searched in the following locations:
    file:/Applications/Android Studio-2.app/Contents/gradle/m2repository/gradle/plugin/info/adavis/qualityChecks/maven-metadata.xml
    file:/Applications/Android Studio-2.app/Contents/gradle/m2repository/gradle/plugin/info/adavis/qualityChecks/
    https://jcenter.bintray.com/gradle/plugin/info/adavis/qualityChecks/maven-metadata.xml
    https://jcenter.bintray.com/gradle/plugin/info/adavis/qualityChecks/
    https://plugins.gradle.org/m2/gradle/plugin/info/adavis/qualityChecks/maven-metadata.xml
    https://plugins.gradle.org/m2/gradle/plugin/info/adavis/qualityChecks/
```

**Comment by adavis** [comment]
It's still available, perhaps you haven't placed the dependencies in the correct order? I have added some screen shots to this issue.

![top_level_build_gradle](https://cloud.githubusercontent.com/assets/141404/17891961/caeca9b4-690c-11e6-9b13-a88845f56404.png)

![app_build_gradle](https://cloud.githubusercontent.com/assets/141404/17891967/d6ba4bf2-690c-11e6-8ccb-e74e70010594.png)

**Comment by pamartineza** [comment]
I think this is not the problem, my config looks pretty much like yours

![android_shoptimix_-_android_shoptimix_-____documents_shoptimix_git_android_shoptimix_](https://cloud.githubusercontent.com/assets/5766641/17895330/0de1ccd2-694d-11e6-8bdb-6197feb6e42b.png)
![app_-_android_shoptimix_-____documents_shoptimix_git_android_shoptimix_](https://cloud.githubusercontent.com/assets/5766641/17895389/4285281c-694d-11e6-82b9-88eb5a155533.png)

**Comment by adavis** [comment]
What if you specify the specific version, use `0.1.3` directly? Or perhaps include the top-level `buildscript` info inside of the app's `build.gradle` file? I just tried it on a random application and it worked for me.

**Comment by pamartineza** [comment]
The same with explicit 0.1.3  or including build script info inside app's gradle file. Maybe you are being able to compile because your computer has a cached version ?¿

**Comment by pamartineza** [comment]
All your repos in bintray seem empty: https://bintray.com/adavis/repositories

**Comment by adavis** [comment]
I just upgraded the plugin to `0.1.4` and did a sync on my project and I was able to get the update and run the tasks, so not sure what's wrong with your setup. You can see the Plugin here: => https://plugins.gradle.org/plugin/info.adavis.qualitychecks. So maybe add it to the `buildscript` there in your app's `build.gradle`.

**Comment by pamartineza** [comment]
0.1.4 works!! thanks for your time
