### ISSUE TITLE
Findbugs task fails on non-Android module

### ISSUE THREAD

**Issue by doubleo2** [adavis/quality-checks#2]
> Execution failed for task ':javalib:findbugs'.
> \> java.io.IOException: No files to analyze could be opened

This is caused by the fact that java modules don't have a `${project.buildDir}/intermediates/classes` folder.

The plugin should either throw an exception when applied to a non-Android project or change it's configuration when applied to a java module.

**Comment by adavis** [comment]
I'll update the docs to point out that this plugin is for Android modules only. Thanks.
